[features]
enabled = ["SIFT", "GLCM", "HU_MOMENTS", "LBP", "HIST"]

[features.GLCM]
levels = 32
distances = [1]
angles = [0, 0.7854, 1.5708, 2.3562]  # [0, π/4, π/2, 3π/4]
symmetric = true
normed = true

[features.HU_MOMENTS]

[features.LBP]
radius = 3
n_points = 24
bins = 59
method = "uniform"

[features.HIST]
bins = 20

[features.SIFT]
n_octaves = 6
n_bins = 10
n_hist = 4
